name: Generate Samsung TV Plus Playlist

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]
    paths: 
      - 'generate_samsung_tvplus.py'
      - '.github/workflows/generate-playlist.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Generate playlist and EPG files
      run: python generate_samsung_tvplus.py
      env:
        # Configuration via environment variables
        REGIONS: 'all'  # Change to specific regions like 'us,uk,ca' if needed
        GROUPS: ''      # Leave empty for all groups, or specify like 'News,Sports'
        INCLUDE_DRM: 'true'
        START_CHNO: '1'
        SORT_BY: 'chno'  # 'chno' or 'name'
        
    - name: Check if files were generated
      run: |
        ls -la output/
        echo "Playlist file size: $(wc -l < output/samsung_tvplus.m3u) lines"
        echo "EPG file size: $(wc -c < output/samsung_tvplus.xml) bytes"
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update Samsung TV Plus playlist and EPG - $(date -u '+%Y-%m-%d %H:%M:%S') UTC"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: samsung-tvplus-files
        path: output/
        retention-days: 30
